/**
 * GabyCursoOpenAPI
 * Especificacion de OpenAPi para el Curso
 *
 * OpenAPI spec version: 1.0
 * Contact: QuinterosGabrielRoberto@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Address { 
    /**
     * Nombre de Calle
     */
    streetName?: string;
    /**
     * Numero de Calle
     */
    streetNumber?: string;
    /**
     * Ciudad/Localidad
     */
    city?: string;
    /**
     * Codigo de Pais de 2 Caracteres
     */
    countryCode?: Address.CountryCodeEnum;
    /**
     * Codigo Postal
     */
    zipCode?: string;
}
export namespace Address {
    export type CountryCodeEnum = 'AR' | 'BR' | 'CH' | 'MX' | 'UK';
    export const CountryCodeEnum = {
        AR: 'AR' as CountryCodeEnum,
        BR: 'BR' as CountryCodeEnum,
        CH: 'CH' as CountryCodeEnum,
        MX: 'MX' as CountryCodeEnum,
        UK: 'UK' as CountryCodeEnum
    };
}