/**
 * GabyCursoOpenAPI
 * Especificacion de OpenAPi para el Curso
 *
 * OpenAPI spec version: 1.0
 * Contact: QuinterosGabrielRoberto@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BeersBrewery } from './beersBrewery';

/**
 * Objeto Cerveza
 */
export interface Beer { 
    readonly id?: string;
    /**
     * Nombre de Cerveza
     */
    name?: string;
    /**
     * Tipo de Cerveza
     */
    style?: Beer.StyleEnum;
    /**
     * Precio por Litro de Cerveza
     */
    price?: number;
    /**
     * Moneda en que Cotiza la Cerveza
     */
    currency?: Beer.CurrencyEnum;
    /**
     * Stock de la Cerveza en litros
     */
    stock?: number;
    brewery?: BeersBrewery;
}
export namespace Beer {
    export type StyleEnum = 'ALE' | 'PALE_ALE' | 'IPA' | 'WHEAT' | 'LAGER';
    export const StyleEnum = {
        ALE: 'ALE' as StyleEnum,
        PALEALE: 'PALE_ALE' as StyleEnum,
        IPA: 'IPA' as StyleEnum,
        WHEAT: 'WHEAT' as StyleEnum,
        LAGER: 'LAGER' as StyleEnum
    };
    export type CurrencyEnum = 'ARS' | 'USD';
    export const CurrencyEnum = {
        ARS: 'ARS' as CurrencyEnum,
        USD: 'USD' as CurrencyEnum
    };
}