/**
 * GabyCursoOpenAPI
 * Especificacion de OpenAPi para el Curso
 *
 * OpenAPI spec version: 1.0
 * Contact: QuinterosGabrielRoberto@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Fabricante de Cervezas
 */
export interface BeersBrewery { 
    /**
     * Nombre del Fabricante
     */
    name?: string;
    /**
     * Ubicacion del Fabricante
     */
    location?: string;
}